title: Andrew Schenk # your name (or website title) here
logo: "/images/LinkedIn profile pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Driven Professional  
  Turning data into stories and actionable insights  
  <br><br>
  <a href="https://www.linkedin.com/in/andrewschenk-pt-mba/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
